#!/usr/bin/env bash
# taskfer-notify

# Use this variable only if you use a non-standard location 
# for the config file, taskferrc. (i.e. not $HOME/.taskfer/taskferrc
# and not /etc/taskferrc.)
configfile=""

# [[ -z $DISPLAY ]] && return

if [[ -z $DISPLAY ]] ; then
    echo "    X needs to be running for this to work."
    exit 1
fi

if [[ -f $HOME/.taskfer/taskferrc ]] ; then
    source "$HOME"/.taskfer/taskferrc
elif [[ -f /etc/taskferrc ]] ; then
    source /etc/taskferrc
elif [[ -n $configfile ]] ; then
    source "$configfile"
else
    echo "    You need to edit this script to set the location
    of the configuration file, taskferrc."
fi


ddt=$(date +%F)
if [[ $(type -p notify-send) ]] ; then
    while read line ; do
        if [[ -n $(echo $line | cut -d"|" -f2 | grep $ddt) ]] ; then
            notify-send -t 7000 "You have tasks listed for today. Check your todo list."
            exit 0
        fi
    done < "$tasklist"
else
    echo "    You need to install the libnotify-bin package 
    for this function to work."
    exit 1
fi
